name: GitHub Actions Demo

on:
  pull_request:
    types: [closed]
jobs:
  pick-github-branch:
    if: github.event.pull_request.merged == true && contains(join(github.event.pull_request.labels.*.name), 'pick-to')
    runs-on: ubuntu-latest
    env:
      GITHUB_ACTION_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: run script
        run: |
          echo "${{ secrets.ROBOT_GITHUB_TOKEN }}" | gh auth login --with-token
          gh release download --repo collides/gh-pick-merge 0.1.0-rc.3 -p 'gh-pick-merge-linux-amd64'
          chmod 777 ./gh-pick-merge-linux-amd64
          ./gh-pick-merge-linux-amd64
