name: GitHub Actions Demo
on:
  pull_request:
    types: [closed]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: run script
        run: |
          curl https://www.baidu.com \
          curl -O https://github.com/collides/gh-pick-merge/releases/download/0.1.0/gh-pick-merge-linux-amd64 \
          chmod 777 ./gh-pick-merge-linux-amd64 \
          ./gh-pick-merge-linux-amd64 \
