name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
        - name: checkout
          uses: actions/checkout@v1
        - name: cargo build
          run: cargo build --release
        - name: cargo run
          run: cargo run

      
