name: GitHub Actions Demo
on:
  pull_request:
    types: [closed]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: run script
        run: curl https://github.com
