name: GitHub Actions Demo
on:
  pull_request:
    types: [closed]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: cargo build
        run: cargo build --release
      - name: cargo run
        run: cargo run
